version: "3.8"

services:
  postgres:
    container_name: postgres-db-cp
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=zhenya_z
      - POSTGRES_DB=cp
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/db.sql

  app:
    container_name: app-db-cp
    build: .
    volumes:
      - ./logs:/logs
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped